# Generated by Django 5.1.7 on 2025-03-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("asset_type", models.CharField(max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(default="style", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("owner", models.CharField(blank=True, max_length=50, null=True)),
                ("base_currency", models.CharField(default="USD", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=50)),
                ("value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("run_date", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.portfolio"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.scenario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("transaction_type", models.CharField(default="BUY", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.asset"
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.portfolio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factor"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["factor", "date"], name="core_factor_factor__d672e9_idx"
                    )
                ],
                "unique_together": {("factor", "date")},
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("close_price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("source", models.CharField(default="unknown", max_length=50)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.asset"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset", "date"], name="core_market_asset_i_070df1_idx"
                    )
                ],
                "unique_together": {("asset", "date")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.asset"
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.portfolio"
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "asset")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("nav", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "daily_return",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.portfolio"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["portfolio", "date"],
                        name="core_portfo_portfol_0ae68c_idx",
                    )
                ],
                "unique_together": {("portfolio", "date")},
            },
        ),
        migrations.CreateModel(
            name="RiskMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("metric_type", models.CharField(max_length=50)),
                ("value", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.portfolio"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["portfolio", "date", "metric_type"],
                        name="core_riskme_portfol_4cfb92_idx",
                    )
                ],
            },
        ),
    ]
